package com.lnathan.village;

import net.minecraft.core.BlockPos;

/**
 * Represents a village that has been discovered by a player.
 *
 * <p>Stores the village's center position in world coordinates and its generated name.
 * Instances are created by {@link VillageRegistry#register(net.minecraft.server.level.ServerPlayer, BlockPos)}
 * and persisted to NBT via {@link #serialize()} / {@link #deserialize(String)}.</p>
 */
public class DiscoveredVillage {

    /** World position of the village center, derived from averaging nearby POI positions. */
    private final BlockPos center;

    /** Human-readable name generated by {@link VillageNamePool#getRandom()}. */
    private final String name;

    /**
     * Creates a discovered village with a known center and name.
     *
     * @param center World position of the village center.
     * @param name   Display name of the village.
     */
    public DiscoveredVillage(BlockPos center, String name) {
        this.center = center;
        this.name = name;
    }

    /**
     * Returns the world position of this village's center.
     *
     * @return The center {@link BlockPos}.
     */
    public BlockPos getCenter() { return center; }

    /**
     * Returns the display name of this village.
     *
     * @return The village name string.
     */
    public String getName() { return name; }

    /**
     * Serializes this village to a compact string suitable for NBT storage.
     *
     * <p>Format: {@code "x,y,z|name"}</p>
     *
     * @return A serialized string representation of this village.
     */
    public String serialize() {
        return center.getX() + "," + center.getY() + "," + center.getZ() + "|" + name;
    }

    /**
     * Deserializes a village from a string previously produced by {@link #serialize()}.
     *
     * <p>Expected format: {@code "x,y,z|name"}</p>
     *
     * @param data The serialized village string.
     * @return A reconstructed {@link DiscoveredVillage} instance.
     * @throws NumberFormatException     if the coordinate values cannot be parsed.
     * @throws ArrayIndexOutOfBoundsException if the string format is malformed.
     */
    public static DiscoveredVillage deserialize(String data) {
        String[] parts = data.split("\\|");
        String[] coords = parts[0].split(",");
        BlockPos pos = new BlockPos(
                Integer.parseInt(coords[0]),
                Integer.parseInt(coords[1]),
                Integer.parseInt(coords[2])
        );
        return new DiscoveredVillage(pos, parts[1]);
    }
}