package com.lnathan.mixin;

import net.minecraft.server.MinecraftServer;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * Placeholder Mixin generated by the Fabric template.
 */
@Mixin(MinecraftServer.class)
public class ExampleMixin {

	/**
	 * Called at the very start of {@code MinecraftServer#loadLevel()}.
	 *
	 * <p>This injection point runs before any level data is loaded, making it
	 * suitable for registering server-side resources that must be available
	 * before the world is fully initialised.
	 *
	 * @param info Mixin callback (unused)
	 */
	@Inject(at = @At("HEAD"), method = "loadLevel")
	private void init(CallbackInfo info) {
		// This code is injected into the start of MinecraftServer.loadLevel()V
	}
}